# Generated by Django 4.1.1 on 2022-10-02 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwitchArray',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('switcharray', models.CharField(blank=True, max_length=256, null=True, verbose_name='Switch Array')),
            ],
        ),
    ]
